FROM ubuntu:26.04 AS builder

ARG UID=1000
ARG GID=1000
ARG USERNAME="kevin"
ENV HOME=/home/$USERNAME

ARG QEMU_VER="11.1.1"

USER root

RUN <<'EOF'
    #!/bin/bash
    set -euo pipefail
    echo ">>> [QEMU] Installing temporary build dependencies..."
    apt-get update && apt-get install --no-install-recommends -y \
        sudo zsh \
        ca-certificates \
        curl \
        tar \
        unzip \
        xz-utils \
        bzip2 \
        locales \
        gzip \
        wget \
        build-essential g++ autoconf automake libtool ccache \
        cmake ninja-build meson pkg-config \
        bc bison flex gawk device-tree-compiler \
        dejagnu expect tcl \
        python3 python3-pip python3-dev python3-setuptools python-is-python3 python3-tomli python3-wheel \
        libaio-dev libbluetooth-dev libcapstone-dev libbrlapi-dev libbz2-dev \
        libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev \
        libibverbs-dev libjpeg8-dev libncurses5-dev libnuma-dev \
        librbd-dev librdmacm-dev \
        libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev libssh-dev \
        libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev \
        valgrind xfslibs-dev libnfs-dev libiscsi-dev \
        guile-3.0-dev libelf-dev libncurses-dev libncursesw5-dev \
        libglib2.0-dev libpixman-1-dev libfdt-dev zlib1g-dev libslirp-dev  liburing-dev \
        libsource-highlight-dev libbabeltrace-dev liblzma-dev libedit-dev \
        libgmp-dev libmpfr-dev libmpc-dev libisl-dev libexpat1-dev libzstd-dev \
        libreadline-dev libffi-dev libgdbm-dev libipt-dev

    #apt-get autoremove --purge -y build-essential ninja-build flex bison
    rm -rf /var/lib/apt/lists/*
EOF

RUN <<'EOF'
    #!/bin/bash
    set -euo pipefail

    TMP_DIR=$(mktemp -d)
    QEMU_URL="https://download.qemu.org/qemu-${QEMU_VER}.tar.xz"
    QEMU_TARGETS="arm-linux-user,armeb-linux-user,aarch64-linux-user,aarch64_be-linux-user,arm-softmmu,aarch64-softmmu,riscv32-softmmu,riscv64-softmmu,riscv32-linux-user,riscv64-linux-user"

    echo ">>> [QEMU] Building from source..."
    curl -fSL "${QEMU_URL}" | tar -xJ -C "${TMP_DIR}"
    cd "${TMP_DIR}/qemu-${QEMU_VER}"
    ./configure --prefix=/opt/qemu --target-list="${QEMU_TARGETS}"
    make -j$(nproc)
    make install

    echo ">>> [QEMU] Purging build artifacts and dependencies..."
    cd /
    rm -rf "${TMP_DIR}"

EOF




# This image contains everything 
FROM kflyn825/tool-base:latest
USER root
ARG UID=1000
ARG GID=1000
ARG USERNAME="kevin"
ENV HOME=/home/$USERNAME
ARG PYTHON_VENV_PATH=/opt/python/venv
ARG WGET_ARGS="-q --show-progress --progress=bar:force:noscroll"

ARG LLVM_VERSION=20
ENV LLVM_VERSION=$LLVM_VERSION

RUN <<'EOF'
    #!/bin/bash
    set -euo pipefail
    echo ">>> [QEMU] Installing temporary build dependencies..."
    apt-get update && apt-get install --no-install-recommends -y \
        software-properties-common \
		lsb-release \
		autoconf \
		automake \
		bison \
		build-essential \
		ca-certificates \
		chrpath \
		cmake \
		cpio \
		device-tree-compiler \
		dfu-util \
		diffstat \
		dos2unix \
		doxygen \
		file \
		flex \
		g++ \
		gawk \
		gcc \
		gcovr \
		gdb \
		gdisk \
		git \
		git-core \
		gnupg \
		gperf \
		graphviz \
		help2man \
		iproute2 \
		lcov \
		libcairo2-dev \
		libfuse3-dev \
		libglib2.0-dev \
		libgtk2.0-0 \
		liblocale-gettext-perl \
		libncurses5-dev \
		libpcap-dev \
		libpopt0 \
		libsdl1.2-dev \
		libsdl2-dev \
		libssl-dev \
		libtool \
		libtool-bin \
		locales \
		make \
		net-tools \
		nodejs \
		npm \
		openssh-client \
		parallel \
		pkg-config \
		python3 \
		python3-dev \
		python3-pip \
		python3-ply \
		python3-setuptools \
		python3-venv \
		python-is-python3 \
		rsync \
		socat \
		srecord \
		sudo \
		texinfo \
		unzip \
		uuid-runtime \
		valgrind \
		wget \
		ovmf \
		xz-utils \
		thrift-compiler


	# Install LLVM and Clang
	#apt-get install --no-install-recommends -y \
	#	clang-${LLVM_VERSION} \
	#	clang-format-${LLVM_VERSION} \
	#	clang-tidy-${LLVM_VERSION} \
	#	clang-tools-${LLVM_VERSION} \
	#	clangd-${LLVM_VERSION} \
	#	libc++-${LLVM_VERSION}-dev \
	#	libclang-rt-${LLVM_VERSION}-dev \
	#	lld-${LLVM_VERSION} \
	#	lldb-${LLVM_VERSION} \
	#	llvm-${LLVM_VERSION} \
	#	llvm-${LLVM_VERSION}-dev

		# Clean up stale packages
	apt-get autoremove --purge -y

	# Clean up local repository
	apt-get clean -y
	rm -rf /var/lib/apt/lists/*
EOF


ENV OVMF_FD_PATH=/usr/share/ovmf/OVMF.fd



# Set up Python virtual environment
RUN <<'EOF'
  
    # Initialise virtual environment
    mkdir -p "${PYTHON_VENV_PATH}"
    python3 -m venv "${PYTHON_VENV_PATH}"

    # Activate virtual environment for subsequent steps in this block
    . "${PYTHON_VENV_PATH}/bin/activate"

    # Install pip package manager
    pip install --no-cache-dir --upgrade pip setuptools wheel

    # Install Zephyr requirements
    pip install --no-cache-dir \
		cryptography>=40.0.0 \
		intelhex \
		click \
		cbor2 \
		setuptools \
		pyyaml \
		pytest \
		jinja2 \
		jsonschema \
		cbor2 \
		click \
		cryptography>=36.0.1 \
		pyasn1 \
		imgtool>=1.9.0 \
		Jinja2>=2.10.3 \
		jsonschema>=3.2.0 \
		PyYAML \
		pyhsslms~=2.0.0 \
		ecdsa \
		kconfiglib \
		networkx~=3.1 \
		pyelftools \
		rich \
		libclang \
        'esptool>=5.0.2' \
        GitPython \
        junitparser \
        junit2html \
        nrf-regtool~=9.0.1 \
        numpy \
        protobuf \
        grpcio-tools \
        PyGithub \
        pylint \
        sh \
        statistics \
        west

    # Run pip check (x86 only for now because it fails on ARM)
    if [ "${HOSTTYPE}" = "x86_64" ]; then
        pip check
    fi
EOF


#copy the QEMU binaries from the builder stage and install runtime dependencies
COPY --from=builder /opt/qemu /opt/qemu
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libcapstone5 \
        libnuma1 \
        liburing2 \
        libiscsi7 \
        libaio1t64 \
        libnfs14 \
        libssh-4 \
        librbd1 \
        librados2 \
		libepoxy0 \
        libsnappy1v5 \
        libslirp0 \
        libvdeplug2t64 \
        libgtk-3-0t64 \
        libvte-2.91-0 \
        libbrlapi0.8 \
    && rm -rf /var/lib/apt/lists/*

USER $USERNAME

CMD ["zsh"]